### ISSUE TITLE
Typescript React Dependencies error

### ISSUE THREAD

**Issue by paveligorevich55** [RabbyHub/rabbykit#12]
That's error i get from React installing with typescript flags:

`npx create-react-app rabbykit --template typescript`

In default `package.json`  - `typescript: 4.9.5`
How to fix that? 

```
$ npm install @rabbit-wallet/rabbykit wagmi@1.4.13 viem@1.21.4
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: rabbykit@0.1.0
npm ERR! Found: typescript@4.9.5
npm ERR! node_modules/typescript
npm ERR!   typescript@"^4.9.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@">=5.0.4" from viem@1.21.4
npm ERR! node_modules/viem
npm ERR!   viem@"1.21.4" from the root project
npm ERR!   peer viem@">=0.3.35" from wagmi@1.4.13
npm ERR!   node_modules/wagmi
npm ERR!     wagmi@"1.4.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by dmy147** [comment]
The latest version of wagmi requires TypeScript v5.0.4 or greater so you'll need to configure CRA to work with that. `create-react-app` is not actively maintained, so it still use typescript@4.9.5, can you try  using [Vite](https://vitejs.dev/guide/) instead?

**Comment by paveligorevich55** [comment]
> The latest version of wagmi requires TypeScript v5.0.4 or greater so you'll need to configure CRA to work with that. `create-react-app` is not actively maintained, so it still use typescript@4.9.5, can you try using [Vite](https://vitejs.dev/guide/) instead?

Problem with wagmi/core on vite react TS... Can't install this package

```

$ npm install wagmi/core@1.4.13--save
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Desktop\testreact\vitetest\wagmi\core@1.4.13--save/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Desktop\testreact\vitetest\wagmi\core@1.4.13--save\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\79104\AppData\Local\npm-cache\_logs\2024-01-09T07_03_24_118Z-debug-0.log

```

**Comment by paveligorevich55** [comment]
Also when i try to config my ConnectionButton 

``` 
"wagmi/connectors/walletConnectLegacy" imported by "@rabby-wallet/rabbykit". Is it installed?
```

**Comment by dmy147** [comment]
> "wagmi/connectors/walletConnectLegacy" imported by "@rabby-wallet/rabbykit". Is it installed?

Thanks for reporting this mistake-import. It will be fixed in the next release. 
now you can try this workarround `npm install @rabby-wallet/rabbykit wagmi@1.4.13 @wagmi/core@1.4.13 viem@1.21.4`

**Comment by paveligorevich55** [comment]
> > "wagmi/connectors/walletConnectLegacy" imported by "@rabby-wallet/rabbykit". Is it installed?
> 
> Thanks for reporting this mistake-import. It will be fixed in the next release. now you can try this workarround `npm install @rabby-wallet/rabbykit wagmi@1.4.13 @wagmi/core@1.4.13 viem@1.21.4`

All working, Thx!
