### ISSUE TITLE
Error can't be used with wagmi 2.x (not specified in package dependency)

### ISSUE THREAD

**Issue by Miguiz** [RabbyHub/rabbykit#14]
When i try this kit i have this error :

✘ [ERROR] Missing "./connectors/walletConnect" specifier in "@wagmi/core" package [plugin vite:dep-pre-bundle]

    node_modules/esbuild/lib/main.js:1374:21:
      1374 │         let result = await callback({
           ╵                      ^

Can you upgrade your kit that can use wagmi 2.x or lock dependency in package.json ?

Ty,

**Comment by dmy147** [comment]
An upgrade to Wagmi v2 is being planned.
Rabbykit is currently based on Wagmi v1. You can specifically install the version. We don’t want these to have multiple versions in the user project, so these are peerDependencies.

**Comment by vvvvvv1vvvvvv** [comment]
closed since already support wagmi v2
