### ISSUE TITLE
Proposition Feature: Can you add optional back button next to close ?

### ISSUE THREAD

**Issue by Miguiz** [RabbyHub/rabbykit#28]
I would like an optionnal button back action in RabbyKitActions or Hooks like close button, if it possible.

Thank

**Comment by dmy147** [comment]
Hi, thank you for your suggestion!

Could you please provide more details?

If you're looking for a hook for closing the Kit modal, maybe you can use `onModalClosed` or `onModalClosedByManualOperation`.

```js
  rabbyKit.open({
    onModalClosed() {
      //code
    },
    onModalClosedByManualOperation() {
      //code
    },
  })
```

**Comment by Miguiz** [comment]
I see sorry, I will explain my case.

I use your modal after one other modal and my previous modal has 2 actions: go back and close.

With your modal I can use the close button for close but I dont have a go back button that could improve my UX

**Comment by dmy147** [comment]
Thank you for your feedback and for sharing more details about your use case! 
I understand the need for a "go back" button to enhance the user experience. 
However, the current design of our Kit focuses on simplicity and alignment with most common use cases. 
While we won't be adding a "go back" button directly to the component at this time, you can consider customizing the modal in your implementation to fit your specific UX needs
