### ISSUE TITLE
Any plans to add Bitcoin connectors?

### ISSUE THREAD

**Issue by Janaka-Steph** [RabbyHub/rabbykit#29]
Any plans to add Bitcoin connectors like here https://github.com/bob-collective/sats-wagmi ?

**Comment by dmy147** [comment]
Thank you for your interest and suggestion! Currently, adding Bitcoin connectors is not on our immediate roadmap. However, we’re always open to contributions from the community or further discussions on how this could be integrated effectively.

If you have any ideas or would like to help contribute, feel free to share a proposal or open a pull request, and we’d be happy to review it!

**Comment by Janaka-Steph** [comment]
Alright, thank you :)
